const ASCII_EMOJIS = {
    "ʘ‿ʘ": [
        { art: "\\˚ㄥ˚\\", name: "Quirky" },
        { art: "☁ ▅▒░☼‿☼░▒▅ ☁", name: "Sunrise" },
        { art: "ˁ˚ᴥ˚ˀ", name: "Bear Friend" },
        { art: "⎦˚◡˚⎣", name: "Boxy Smile" },
        { art: "<*_*>", name: "Starry Eyes" },
        { art: "(-(-_(-_-)_-)-)", name: "The Squad" },
        { art: "(✿ ♥‿♥)", name: "Lovely" },
        { art: "㋡", name: "Chill" },
        { art: "(⌒▽⌒)", name: "Joy" },
        { art: "(◔/‿\\◔)", name: "Derp Stare" },
        { art: "(⋗_⋖)", name: "Ouch" },
        { art: "ة_ة", name: "Dazed" },
        { art: "\\(^-^)/", name: "Yay" },
        { art: "◕_◕", name: "Puppy Eyes" },
        { art: "(っ◕‿◕)っ", name: "Gimme Hug" },
        { art: "( ͠° ͟ʖ ͡°)", name: "Suspicious" },
        { art: "ʘ‿ʘ", name: "Innocent Face" },
        { art: "(｡◕‿◕｡)", name: "Cute Big Eyes" },
        { art: "☜(⌒▽⌒)☞", name: "Excited" },
        { art: "ヽ(´▽`)/", name: "Happy" },
        { art: "ヽ(´ー｀)ノ", name: "Glory" },
        { art: "⊂(◉‿◉)つ", name: "Kirby" },
        { art: "(づ￣ ³￣)づ", name: "Hugger" },
        { art: "“ヽ(´▽｀)ノ”", name: "TGIF" },
        { art: "♥‿♥", name: "Love" },
        { art: "( ˘ ³˘)♥", name: "Kissing" },
        { art: "\\(ᵔᵕᵔ)/", name: "Happy Hug" },
        { art: "ᴖ̮ ̮ᴖ", name: "Resting Eyes" },
        { art: "-`ღ´-", name: "Love 2" }
    ],
    "ಠ_ಠ": [
        { art: "ಠ_ಠ", name: "Disapproval" },
        { art: "(╬ ಠ益ಠ)", name: "Angry" },
        { art: "ლ(ಠ益ಠლ)", name: "At What Cost" },
        { art: "ಠ‿ಠ", name: "Devious" },
        { art: "ಥ_ಥ", name: "Crying" },
        { art: "ಥ﹏ಥ", name: "Breakdown" },
        { art: "٩◔̯◔۶", name: "Disagree" },
        { art: "(´･_･`)", name: "Worried" },
        { art: "(ಥ⌣ಥ)", name: "Sad" },
        { art: "눈_눈", name: "Sleepy" },
        { art: "( ఠ ͟ʖ ఠ)", name: "Judging" },
        { art: "( ͡ಠ ʖ̯ ͡ಠ)", name: "Tired" },
        { art: "( ಠ ʖ̯ ಠ)", name: "Dislike" },
        { art: "(ᵟຶ︵ ᵟຶ)", name: "Sad Crying" }
    ],
    "(っ▀¯▀)つ": [
        { art: "¯\\_(ツ)_/¯", name: "Shrug" },
        { art: "( ͡° ͜ʖ ͡°)", name: "Lenny Face" },
        { art: "ᕙ(⇀‸↼‶)ᕗ", name: "Flexing" },
        { art: "┌(ㆆ㉨ㆆ)ʃ", name: "Dancing" },
        { art: "(•̀ᴗ•́)و ̑̑", name: "Winning" },
        { art: "(☞ﾟヮﾟ)☞", name: "Pointing" },
        { art: "(っ▀¯▀)つ", name: "Stunna Shades" },
        { art: "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ", name: "Wizard" },
        { art: "(╯°□°）╯︵ ┻━┻", name: "Table Flip" },
        { art: "┬─┬﻿ ノ( ゜-゜ノ)", name: "Put Table Back" },
        { art: "┬─┬⃰͡ (ᵔᵕᵔ͜ )", name: "Tidy Table" },
        { art: "(ง'̀-'́)ง", name: "Fight" }
    ],
    "ʕ•ᴥ•ʔ": [
        { art: "ʕ•ᴥ•ʔ", name: "Cute Bear" },
        { art: "ʕᵔᴥᵔʔ", name: "Squinting Bear" },
        { art: "ʕ •`ᴥ•´ʔ", name: "GTFO Bear" },
        { art: "V•ᴥ•V", name: "Dog" },
        { art: "ฅ^•ﻌ•^ฅ", name: "Meow" },
        { art: "ʕ •́؈•̀ ₎", name: "Winnie" },
        { art: "{•̃_•̃}", name: "Robot" },
        { art: "(ᵔᴥᵔ)", name: "Seal" },
        { art: "[¬º-°]¬", name: "Zombie" },
        { art: "ƪ(ړײ)‎ƪ​​", name: "Creeper" },
    ],
    "⊙﹏⊙": [
        { art: "¯\\(°_o)/¯", name: "Meh" },
        { art: "⊙﹏⊙", name: "Discombobulated" },
        { art: "¯\\_(⊙︿⊙)_/¯", name: "Sad Confused" },
        { art: "¿ⓧ_ⓧﮌ", name: "Confused" },
        { art: "(⊙.☉)7", name: "Confused Scratch" },
        { art: "٩(๏_๏)۶", name: "Staring" },
        { art: "(⊙_◎)", name: "Zoned" },
        { art: "ミ●﹏☉ミ", name: "Crazy" },
        { art: "(Ծ‸ Ծ)", name: "Questionable" },
        { art: "⥀.⥀", name: "Eye Roll" },
        { art: "♨_♨", name: "Unseen" },
        { art: "(._.)", name: "Looking Down" }
    ]
};
